#!/bin/bash
sudo apt -y install xdotool wmctrl pavucontrol arandr
mkdir ~/bin > /dev/null 2>&1
ln -s move-to-next-monitor ~/bin/move-to-next-monitor
chmod a+x ~/bin/move-to-next-monitor
ln -s lubuntu-rc.xml ~/.config/openbox/lubuntu-rc.xml
sudo bash -c "cat pc > /usr/share/X11/xkb/symbols/pc"
