#!/bin/bash
sudo apt install xdotool wmctrl pavucontrol arandr
mkdir ~/bin > /dev/null 2>&1
cat move-to-next-monitor > ~/bin/move-to-next-monitor
chmod a+x ~/bin/move-to-next-monitor
cat lubuntu-rc.xml > ~/.config/openbox/lubuntu-rc.xml
sudo cat pc > /usr/share/X11/xkb/symbols/pc