#!/bin/bash
sudo apt -y install emacs
rm ~/.emacs > /dev/null 2>&1
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
ln -s `pwd`/.spacemacs ~/.spacemacs
ln -s `pwd`/.fmacs ~/.fmacs
sudo apt -y install python3-pip python-pip && \
pip install pylint flake8 autoflake isort && \
pip3 install pylint flake8 autoflake isort
exit 0
