#!/bin/bash
sudo add-apt-repository  ppa:klaus-vormweg/awesome -y
sudo apt update
sudo apt install -y awesome
ln -s `pwd`/awesome ~/.config/awesome
ln -s `pwd`/Xmodmap ~/.Xmodmap
ln -s `pwd`/xsession ~/.xsession
ln -s `pwd`/xinitrc ~/.xinitrc
cd ./awesome/lux && sudo make install && sudo lux
