#!/bin/bash
version=$(lsb_release -a | grep "Release" | awk '{print $2}')
if [ $version == "20.04" ]; then
  sudo apt install -y awesome
else
  sudo add-apt-repository  ppa:klaus-vormweg/awesome -y
  sudo apt update
  sudo apt install -y awesome make
  mkdir -p ~/Pictures/screenshots/
  ln -s `pwd`/awesome ~/.config/awesome
  cd ./awesome/lux && sudo make install && sudo lux
fi
