#!/bin/bash
sudo apt -y install curl && \
wget https://www.privateinternetaccess.com/installer/pia-nm.sh && \
sudo bash pia-nm.sh && \
sudo apt -y install network-manager-openvpn-gnome && \
echo "Please configure the added VPNs with your account password!"
