alias ros="cd ~/code/catkin_ws; source devel/setup.bash"
alias service_robot_ip_setup="source service_robot_ip_setup"
alias realsense_node="cd ~/code/realsense_ws; source devel/setup.bash; roslaunch realsense2_camera rs_camera.launch enable_pointcloud:=true camera:='rs_camera'"
alias kinect_node="cd ~/code/realsense_ws; source devel/setup.bash; roslaunch openni_launch openni.launch"
alias clion=" ~/clion-2019.2.4/bin/clion.sh &"
