#!/bin/bash
touch ~/.bash_history
sudo chown `whoami` ~/.bash_history
rm ~/.bashrc
ln -s `pwd`/.bashrc ~/.bashrc
ln -s `pwd`/.bash_aliases ~/.bash_aliases
ln -s `pwd`/.bash_eternal_history ~/.bash_eternal_history
exit 0
