#!/bin/bash
sudo apt install -y awesome && (mkdir ~/bin > /dev/null 2>&1 || true) && \
mkdir ~/.config/awesome && \
cat rc.lua > ~/.config/awesome/rc.lua && \
cat theme.lua > ~/.config/awesome/theme.lua && \
cp -r battery-widget/ ~/.config/awesome/
sudo chown `whoami` ~/.bash_history && \
mkdir ~/code
