#!/bin/bash
sudo apt install -y awesome && (mkdir ~/bin > /dev/null 2>&1 || true) && \
mkdir ~/.config/awesome && \
cat rc.lua > ~/.config/awesome/rc.lua && \
cat theme.lua > ~/.config/awesome/theme.lua && \
cp *.png ~/.config/awesome/ && \
cp -r battery-widget/ ~/.config/awesome/
git clone https://github.com/Ventto/lux.git ~/.config/awesome/lux
cd ~/.config/awesome/lux && sudo make install && sudo lux
sudo chown `whoami` ~/.bash_history && \
mkdir ~/code
