#!/bin/bash
sudo apt -y install clang g++ qtbase5-dev cmake libpopt-dev \
    libeigen3-dev libgoogle-perftools-dev kcachegrind valgrind libprotobuf-dev \
    protobuf-compiler libsuitesparse-dev libgoogle-glog-dev python3-numpy \
    python3-scipy python3-matplotlib python3-pip python-setuptools python-dev \
    libblas-dev liblapack-dev libopenmpi-dev build-essential\
    qt4-default libqt4-dev qt4-dev-tools libiomp-dev clang-format whiptail\
    imagemagick cimg-dev kdevelop &&\
    sudo apt install libgtest0 libgtest-dev && \
    sudo apt install libgtest-dev  && \
    cd /usr/src/gtest && \
    sudo mkdir build  && \
    sudo cmake ..  && \
    sudo make -j  && \
    sudo cp libgtest* /usr/lib/  && \
    cd .. && \
    sudo rm -rf build/  && \

