#!/bin/bash
pushd ~/code && \
    git clone git@github.com:RoboCup-SSL/ssl-vision.git ssl-vision && \
    pushd ssl-vision && \
    ./InstallPackagesUbuntu.sh && make -j`nproc` && \
    popd && \
    git clone git@github.com:umass-amrl/minutebots.git minutebots && \
    pushd minutebots && \
    ./InstallPackages && make -j`nproc` && \
    popd && \
popd
